name: '[CI/A] CI Pre Merge App'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      # - name: Lint
      #   run: npm run lint

      - name: Build
        run: npm run build
